//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalFarmer2.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalFarmer2.Shared.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Account_Create_Account {
            get {
                return ResourceManager.GetString("Account_Create_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password isn&apos;t correct.
        /// </summary>
        internal static string Account_Error_Login {
            get {
                return ResourceManager.GetString("Account_Error_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string Account_My_Acccount {
            get {
                return ResourceManager.GetString("Account_My_Acccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alerts.
        /// </summary>
        internal static string Alert_All_Alerts {
            get {
                return ResourceManager.GetString("Alert_All_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Here you easy find local farmers..
        /// </summary>
        internal static string Dashboard_Hello {
            get {
                return ResourceManager.GetString("Dashboard_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are u need fresh vegetables or preserve? Check you region and buy from farmhouse..
        /// </summary>
        internal static string Dashboard_Hello2 {
            get {
                return ResourceManager.GetString("Dashboard_Hello2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Farmer.
        /// </summary>
        internal static string Dashboard_LocalFarmer {
            get {
                return ResourceManager.GetString("Dashboard_LocalFarmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add farmhouse.
        /// </summary>
        internal static string Farmhouse_Add_Farmhouse {
            get {
                return ResourceManager.GetString("Farmhouse_Add_Farmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit farmhouse.
        /// </summary>
        internal static string Farmhouse_Edit_Farmhouse {
            get {
                return ResourceManager.GetString("Farmhouse_Edit_Farmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List farmhouses.
        /// </summary>
        internal static string Farmhouse_List_Farmhouses {
            get {
                return ResourceManager.GetString("Farmhouse_List_Farmhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Hey {
            get {
                return ResourceManager.GetString("Hey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        internal static string Product_Add_Product {
            get {
                return ResourceManager.GetString("Product_Add_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My products.
        /// </summary>
        internal static string Product_My_Products {
            get {
                return ResourceManager.GetString("Product_My_Products", resourceCulture);
            }
        }
    }
}
