//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalFarmer2.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalFarmer2.Shared.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Account_Create_Account {
            get {
                return ResourceManager.GetString("Account_Create_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string Account_Email_Address {
            get {
                return ResourceManager.GetString("Account_Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password isn&apos;t correct.
        /// </summary>
        internal static string Account_Error_Login {
            get {
                return ResourceManager.GetString("Account_Error_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string Account_Full_Name {
            get {
                return ResourceManager.GetString("Account_Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Account_Login {
            get {
                return ResourceManager.GetString("Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Account_Logout {
            get {
                return ResourceManager.GetString("Account_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string Account_My_Account {
            get {
                return ResourceManager.GetString("Account_My_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Account_Password_Confirm {
            get {
                return ResourceManager.GetString("Account_Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your details.
        /// </summary>
        internal static string Account_Start_Text {
            get {
                return ResourceManager.GetString("Account_Start_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alerts.
        /// </summary>
        internal static string Alert_All_Alerts {
            get {
                return ResourceManager.GetString("Alert_All_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Alert_Message {
            get {
                return ResourceManager.GetString("Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        internal static string Button_Add_Image {
            get {
                return ResourceManager.GetString("Button_Add_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All products.
        /// </summary>
        internal static string Button_All_Products {
            get {
                return ResourceManager.GetString("Button_All_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        internal static string Button_Basic_Info {
            get {
                return ResourceManager.GetString("Button_Basic_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide photo.
        /// </summary>
        internal static string Button_Hide_Photo {
            get {
                return ResourceManager.GetString("Button_Hide_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open photo.
        /// </summary>
        internal static string Button_Open_Photo {
            get {
                return ResourceManager.GetString("Button_Open_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other products.
        /// </summary>
        internal static string Button_Other_Products {
            get {
                return ResourceManager.GetString("Button_Other_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize information.
        /// </summary>
        internal static string Button_Prize_Info {
            get {
                return ResourceManager.GetString("Button_Prize_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show photo.
        /// </summary>
        internal static string Button_Show_Photo {
            get {
                return ResourceManager.GetString("Button_Show_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Dashboard_Contact {
            get {
                return ResourceManager.GetString("Dashboard_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard_Dashboard {
            get {
                return ResourceManager.GetString("Dashboard_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites farmhouses.
        /// </summary>
        internal static string Dashboard_Favorites_Farmhouses {
            get {
                return ResourceManager.GetString("Dashboard_Favorites_Farmhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Here you easy find local farmers..
        /// </summary>
        internal static string Dashboard_Hello {
            get {
                return ResourceManager.GetString("Dashboard_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are u need fresh vegetables or preserve? Check you region and buy from farmhouse..
        /// </summary>
        internal static string Dashboard_Hello2 {
            get {
                return ResourceManager.GetString("Dashboard_Hello2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Farmer.
        /// </summary>
        internal static string Dashboard_LocalFarmer {
            get {
                return ResourceManager.GetString("Dashboard_LocalFarmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Dashboard_Map {
            get {
                return ResourceManager.GetString("Dashboard_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My opinions.
        /// </summary>
        internal static string Dashboard_My_Opinions {
            get {
                return ResourceManager.GetString("Dashboard_My_Opinions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        internal static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add farmhouse.
        /// </summary>
        internal static string Farmhouse_Add_Farmhouse {
            get {
                return ResourceManager.GetString("Farmhouse_Add_Farmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Farmhouse_Address {
            get {
                return ResourceManager.GetString("Farmhouse_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact form.
        /// </summary>
        internal static string Farmhouse_Contact_Form {
            get {
                return ResourceManager.GetString("Farmhouse_Contact_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit farmhouse.
        /// </summary>
        internal static string Farmhouse_Edit_Farmhouse {
            get {
                return ResourceManager.GetString("Farmhouse_Edit_Farmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is open.
        /// </summary>
        internal static string Farmhouse_IsOpen {
            get {
                return ResourceManager.GetString("Farmhouse_IsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Farmhouse_Latitude {
            get {
                return ResourceManager.GetString("Farmhouse_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List farmhouses.
        /// </summary>
        internal static string Farmhouse_List_Farmhouses {
            get {
                return ResourceManager.GetString("Farmhouse_List_Farmhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Farmhouse_Longitude {
            get {
                return ResourceManager.GetString("Farmhouse_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Farmhouse_Message {
            get {
                return ResourceManager.GetString("Farmhouse_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment methods.
        /// </summary>
        internal static string Farmhouse_Payment_Methods {
            get {
                return ResourceManager.GetString("Farmhouse_Payment_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Farmhouse_Phone {
            get {
                return ResourceManager.GetString("Farmhouse_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmhouse photo.
        /// </summary>
        internal static string Farmhouse_Photo {
            get {
                return ResourceManager.GetString("Farmhouse_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Farmhouse_Send {
            get {
                return ResourceManager.GetString("Farmhouse_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string Farmhouse_Send_Message {
            get {
                return ResourceManager.GetString("Farmhouse_Send_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Farmhouse_Subject {
            get {
                return ResourceManager.GetString("Farmhouse_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Farmhouse_Subscribe {
            get {
                return ResourceManager.GetString("Farmhouse_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Filter_Only_Active {
            get {
                return ResourceManager.GetString("Filter_Only_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string Filter_Only_Archive {
            get {
                return ResourceManager.GetString("Filter_Only_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Hey {
            get {
                return ResourceManager.GetString("Hey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change marker.
        /// </summary>
        internal static string Map_Change_Marker {
            get {
                return ResourceManager.GetString("Map_Change_Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map with all farmhouses.
        /// </summary>
        internal static string Map_With_All_Farmhouses {
            get {
                return ResourceManager.GetString("Map_With_All_Farmhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        internal static string Note_Add_Note {
            get {
                return ResourceManager.GetString("Note_Add_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit note.
        /// </summary>
        internal static string Note_Edit_Note {
            get {
                return ResourceManager.GetString("Note_Edit_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add opinion.
        /// </summary>
        internal static string Opinion_Add_Opinion {
            get {
                return ResourceManager.GetString("Opinion_Add_Opinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Opinion_Comment {
            get {
                return ResourceManager.GetString("Opinion_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set star and add your opinion.
        /// </summary>
        internal static string Opinion_Placeholder {
            get {
                return ResourceManager.GetString("Opinion_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Opinion_Rating {
            get {
                return ResourceManager.GetString("Opinion_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your opinion!.
        /// </summary>
        internal static string Opinion_Your_Opinion {
            get {
                return ResourceManager.GetString("Opinion_Your_Opinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        internal static string Product_Add_Product {
            get {
                return ResourceManager.GetString("Product_Add_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        internal static string Product_Edit_Product {
            get {
                return ResourceManager.GetString("Product_Edit_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal amount.
        /// </summary>
        internal static string Product_Minimal_Amount {
            get {
                return ResourceManager.GetString("Product_Minimal_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My products.
        /// </summary>
        internal static string Product_My_Products {
            get {
                return ResourceManager.GetString("Product_My_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product photo.
        /// </summary>
        internal static string Product_Photo {
            get {
                return ResourceManager.GetString("Product_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize for 1 piece.
        /// </summary>
        internal static string Product_Prize_One {
            get {
                return ResourceManager.GetString("Product_Prize_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products all.
        /// </summary>
        internal static string Product_Products_All {
            get {
                return ResourceManager.GetString("Product_Products_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total quantity.
        /// </summary>
        internal static string Product_Total_Quantity {
            get {
                return ResourceManager.GetString("Product_Total_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page.
        /// </summary>
        internal static string Table_Rows_Per_Page {
            get {
                return ResourceManager.GetString("Table_Rows_Per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is required field.
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string X_Action {
            get {
                return ResourceManager.GetString("X_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string X_Active {
            get {
                return ResourceManager.GetString("X_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string X_Alerts {
            get {
                return ResourceManager.GetString("X_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string X_Archive {
            get {
                return ResourceManager.GetString("X_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure delete this.
        /// </summary>
        internal static string X_Are_You_Sure_Delete_This {
            get {
                return ResourceManager.GetString("X_Are_You_Sure_Delete_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure edit this.
        /// </summary>
        internal static string X_Are_You_Sure_Edit_This {
            get {
                return ResourceManager.GetString("X_Are_You_Sure_Edit_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string X_Cancel {
            get {
                return ResourceManager.GetString("X_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string X_Contact {
            get {
                return ResourceManager.GetString("X_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string X_Date {
            get {
                return ResourceManager.GetString("X_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string X_Delete {
            get {
                return ResourceManager.GetString("X_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string X_Description {
            get {
                return ResourceManager.GetString("X_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string X_Details {
            get {
                return ResourceManager.GetString("X_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string X_Edit {
            get {
                return ResourceManager.GetString("X_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmhouse.
        /// </summary>
        internal static string X_Farmhouse {
            get {
                return ResourceManager.GetString("X_Farmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmhouses.
        /// </summary>
        internal static string X_Farmhouses {
            get {
                return ResourceManager.GetString("X_Farmhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string X_Loading {
            get {
                return ResourceManager.GetString("X_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string X_Name {
            get {
                return ResourceManager.GetString("X_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string X_Note {
            get {
                return ResourceManager.GetString("X_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string X_Notes {
            get {
                return ResourceManager.GetString("X_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opnion.
        /// </summary>
        internal static string X_Opinion {
            get {
                return ResourceManager.GetString("X_Opinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinions.
        /// </summary>
        internal static string X_Opinions {
            get {
                return ResourceManager.GetString("X_Opinions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string X_Product {
            get {
                return ResourceManager.GetString("X_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string X_Products {
            get {
                return ResourceManager.GetString("X_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string X_Save {
            get {
                return ResourceManager.GetString("X_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string X_Search {
            get {
                return ResourceManager.GetString("X_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string X_Subscription {
            get {
                return ResourceManager.GetString("X_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string X_Text {
            get {
                return ResourceManager.GetString("X_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string X_Title {
            get {
                return ResourceManager.GetString("X_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string X_Type {
            get {
                return ResourceManager.GetString("X_Type", resourceCulture);
            }
        }
    }
}
